name: C++ Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up C++ compiler
        uses: aminya/setup-cpp@v1
        with:
          compiler: g++ # usa g++ em todas as plataformas

      - name: Build with Makefile
        run: |
          make all
        shell: bash

      - name: Build all examples
        run: |
          make examples
        shell: bash

      - name: Run main program (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ./bin/program || true
        shell: bash

      - name: Run main program (Windows)
        if: runner.os == 'Windows'
        run: |
          .\\bin\\program.exe || exit 0
        shell: pwsh

      - name: Clean build
        run: |
          make clean
        shell: bash
